#!/bin/bash
DEST_DIR="/mnt/g/My Drive/anduril firmware/"`date +%F_%H_%M_%S`
mkdir "$DEST_DIR"

for i in \
    "emisar-2ch d4v2-tintramp-sst20" \
    "emisar-2ch d4v2-tintramp-519a" \
    "emisar-2ch d4v2-astro" \
    "emisar-2ch d4sv2-flood-throw" \
    "emisar-2ch d2-uv" \
    "emisar-2ch d2-stock-uv" \
    "emisar-d3aa 519a-5700k-dd" \
    "emisar-d3aa candle" \
    "emisar-d3aa stock" \
    "noctigon-dm11/boost d1k-ffl707a" \
    "noctigon-dm11/boost stock" \
    "noctigon-k1/sbt90 d1-sfn60" \
    "noctigon-k1/sbt90 stock" \
    "noctigon-kr4 sst20" \
    "noctigon-kr4 stock" \
    "noctigon-kr4/219b d4v2" \
    "noctigon-kr4/219b stock" \
    "noctigon-kr4/nofet d4v2" \
    "noctigon-kr4/nofet stock"
do
    set -- $i  # Convert the above into $1, $2...
    dir="$1"
    name="$2"
    model="${dir//\//-}"
    echo "[48;5;236m[92m >>>" Building $model for $name... ">>> [0m"
    cp hw/hank/$dir/config-$name.h hw/hank/$dir/config-fwiffo.h
    ./make hank-$model' '
    rm hw/hank/$dir/config-fwiffo.h
    touch hw/hank/$dir/config-fwiffo.h
    cp hex/anduril.hank-$model.hex "$DEST_DIR"/${model}_${name}.hex
    echo "[48;5;236m[94m >>>" Built "$DEST_DIR"/${model}_${name}.hex ">>> [0m"
    echo
done

